service: serverless-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x

functions:
  login:
    handler: functions/login
    events:
      - httpApi:
          path: /login
          method: POST

plugins:
  - serverless-plugin-typescript
